"""Initial Architecture

Revision ID: 58d36224637d
Revises: 
Create Date: 2026-09-27 14:41:03.723842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58d36224637d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('standard_number', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_hash')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_standard_number'), 'documents', ['standard_number'], unique=False)
    op.create_table('laboratories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('supported_standards', sa.JSON(), nullable=True),
    sa.Column('supported_tests', sa.JSON(), nullable=True),
    sa.Column('accreditation', sa.String(), nullable=True),
    sa.Column('recognition_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laboratories_id'), 'laboratories', ['id'], unique=False)
    op.create_table('licence_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cml_number', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('product_scope', sa.Text(), nullable=True),
    sa.Column('standard', sa.String(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licence_records_cml_number'), 'licence_records', ['cml_number'], unique=True)
    op.create_index(op.f('ix_licence_records_id'), 'licence_records', ['id'], unique=False)
    op.create_table('standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standard_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('scheme', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standards_id'), 'standards', ['id'], unique=False)
    op.create_index(op.f('ix_standards_standard_number'), 'standards', ['standard_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('MANUFACTURER', 'CONSUMER', 'ADMIN', name='userrole'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('clause_number', sa.String(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.create_table('manufacturer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('enterprise_type', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_manufacturer_profiles_id'), 'manufacturer_profiles', ['id'], unique=False)
    op.create_table('qcos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('standard_id')
    )
    op.create_index(op.f('ix_qcos_id'), 'qcos', ['id'], unique=False)
    op.create_table('test_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(), nullable=False),
    sa.Column('clause', sa.String(), nullable=True),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('R', 'S', name='testrequirementtype'), nullable=True),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_requirements_id'), 'test_requirements', ['id'], unique=False)
    op.create_table('product_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('usage', sa.String(), nullable=True),
    sa.Column('extracted_attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_profiles_id'), 'product_profiles', ['id'], unique=False)
    op.create_table('certification_journeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer_profiles.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certification_journeys_id'), 'certification_journeys', ['id'], unique=False)
    op.create_table('factory_readiness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('assessment_data', sa.JSON(), nullable=True),
    sa.Column('critical_gaps', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer_profiles.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factory_readiness_id'), 'factory_readiness', ['id'], unique=False)
    op.create_table('product_standard_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('matching_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product_profiles.id'], ),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_standard_mappings_id'), 'product_standard_mappings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_standard_mappings_id'), table_name='product_standard_mappings')
    op.drop_table('product_standard_mappings')
    op.drop_index(op.f('ix_factory_readiness_id'), table_name='factory_readiness')
    op.drop_table('factory_readiness')
    op.drop_index(op.f('ix_certification_journeys_id'), table_name='certification_journeys')
    op.drop_table('certification_journeys')
    op.drop_index(op.f('ix_product_profiles_id'), table_name='product_profiles')
    op.drop_table('product_profiles')
    op.drop_index(op.f('ix_test_requirements_id'), table_name='test_requirements')
    op.drop_table('test_requirements')
    op.drop_index(op.f('ix_qcos_id'), table_name='qcos')
    op.drop_table('qcos')
    op.drop_index(op.f('ix_manufacturer_profiles_id'), table_name='manufacturer_profiles')
    op.drop_table('manufacturer_profiles')
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_standards_standard_number'), table_name='standards')
    op.drop_index(op.f('ix_standards_id'), table_name='standards')
    op.drop_table('standards')
    op.drop_index(op.f('ix_licence_records_id'), table_name='licence_records')
    op.drop_index(op.f('ix_licence_records_cml_number'), table_name='licence_records')
    op.drop_table('licence_records')
    op.drop_index(op.f('ix_laboratories_id'), table_name='laboratories')
    op.drop_table('laboratories')
    op.drop_index(op.f('ix_documents_standard_number'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
